apiVersion: v1
kind: ConfigMap
metadata:
  name: AgroLogistic-config
data:
  api_gateway_url: "https://api.AgroLogistic.com"
  node_env: "production"
  log_level: "info"
  redis_host: "redis-master.AgroLogistic.svc.cluster.local"
  redis_port: "6379"
  db_host: "postgres-primary.AgroLogistic.svc.cluster.local"
  db_port: "5432"
  db_name: "AgroLogistic"
  elasticsearch_url: "http://elasticsearch.AgroLogistic.svc.cluster.local:9200"
  kafka_brokers: "kafka.AgroLogistic.svc.cluster.local:9092"
  jaeger_endpoint: "http://jaeger-collector.monitoring.svc.cluster.local:14268/api/traces"
