apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: AgroLogistic

resources:
  - ../../base/frontend.yml
  - ../../base/services.yml
  - configmap.yml
  - secrets.yml

images:
  - name: ghcr.io/AgroLogistic/platform
    newTag: latest
  - name: ghcr.io/AgroLogistic/auth-service
    newTag: latest
  - name: ghcr.io/AgroLogistic/product-service
    newTag: latest
  - name: ghcr.io/AgroLogistic/order-service
    newTag: latest
  - name: ghcr.io/AgroLogistic/payment-service
    newTag: latest

replicas:
  - name: AgroLogistic-web
    count: 3
  - name: auth-service
    count: 2
  - name: product-service
    count: 2
  - name: order-service
    count: 2
  - name: payment-service
    count: 2

commonLabels:
  environment: production
  app.kubernetes.io/part-of: AgroLogistic

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/serviceAccountName
        value: AgroLogistic-sa
