apiVersion: v1
kind: ConfigMap
metadata:
  name: AgroLogistic-config
data:
  api_gateway_url: "https://api-staging.AgroLogistic.com"
  node_env: "staging"
  log_level: "debug"
  redis_host: "redis-master.AgriLogistic-staging.svc.cluster.local"
  redis_port: "6379"
  db_host: "postgres-primary.AgriLogistic-staging.svc.cluster.local"
  db_port: "5432"
  db_name: "AgroLogistic"
  elasticsearch_url: "http://elasticsearch.AgriLogistic-staging.svc.cluster.local:9200"
  kafka_brokers: "kafka.AgriLogistic-staging.svc.cluster.local:9092"
  jaeger_endpoint: "http://jaeger-collector.monitoring.svc.cluster.local:14268/api/traces"
