apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: AgriLogistic-staging

resources:
  - ../../base
  - configmap.yml
  - secrets.yml

images:
  - name: ghcr.io/AgroLogistic/platform
    newName: ghcr.io/AgroLogistic/platform
    newTag: latest
  - name: ghcr.io/AgroLogistic/auth-service
    newTag: latest
  - name: ghcr.io/AgroLogistic/product-service
    newTag: latest
  - name: ghcr.io/AgroLogistic/order-service
    newTag: latest
  - name: ghcr.io/AgroLogistic/payment-service
    newTag: latest

replicas:
  - name: AgroLogistic-web
    count: 1

commonLabels:
  environment: staging
  app.kubernetes.io/part-of: AgroLogistic

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/serviceAccountName
        value: AgroLogistic-sa
